IF EXISTS( SELECT TABLE_NAME from INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ADDRESSTYPE' )
    DROP TABLE ADDRESSTYPE;
GO

CREATE TABLE CVGS.dbo.ADDRESSTYPE(
             AddressTypeId    INT IDENTITY( 1,1 ) PRIMARY KEY
           , AddressTypeName  NVARCHAR( 64 ) NOT NULL
);
GO