IF EXISTS( SELECT TABLE_NAME from INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ROLE' )
    DROP TABLE ROLE;
GO

CREATE TABLE CVGS.dbo.ROLE(
             RoleId        INT IDENTITY( 1,1 ) PRIMARY KEY
           , RoleName      NVARCHAR( 64 ) NOT NULL
);
GO