//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public int AddressId { get; set; }
        public int MemberId { get; set; }
        public string StreetAddress { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> ProvStateId { get; set; }
        public int CountryId { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual MEMBER MEMBER { get; set; }
        public virtual PROVSTATE PROVSTATE { get; set; }
    }
}
