//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADDRESS()
        {
            this.ORDERHEADERs = new HashSet<ORDERHEADER>();
            this.ORDERHEADERs1 = new HashSet<ORDERHEADER>();
        }
    
        public int AddressId { get; set; }
        public int MemberId { get; set; }
        public string StreetAddress { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public int ProvStateId { get; set; }
        public int AddressTypeId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
        public virtual PROVSTATE PROVSTATE { get; set; }
        public virtual ADDRESSTYPE ADDRESSTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERHEADER> ORDERHEADERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERHEADER> ORDERHEADERs1 { get; set; }
    }
}
