//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDITCARD
    {
        public int CardId { get; set; }
        public int MemberId { get; set; }
        public string CardNumber { get; set; }
        public string NameOnCard { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
    }
}
