//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRIENDSHIP
    {
        public int Member1Id { get; set; }
        public int Member2Id { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
        public virtual MEMBER MEMBER1 { get; set; }
    }
}
