//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAME()
        {
            this.PLATFORMs = new HashSet<PLATFORM>();
        }
    
        public int GameId { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public string Developer { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public bool DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLATFORM> PLATFORMs { get; set; }
    }
}
