//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER_EVENT
    {
        public int MemberId { get; set; }
        public int EventId { get; set; }
        public Nullable<System.DateTime> DateRegistered { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
