//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBER()
        {
            this.MEMBER_EVENT = new HashSet<MEMBER_EVENT>();
        }
    
        public int MemberId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public byte[] pwd { get; set; }
        public string FavPlatform { get; set; }
        public string FavCategory { get; set; }
        public string FavGame { get; set; }
        public string FavQuote { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public bool ActiveStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBER_EVENT> MEMBER_EVENT { get; set; }
    }
}
