//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERITEM
    {
        public int OrderId { get; set; }
        public int GameId { get; set; }
        public int Quantity { get; set; }
    
        public virtual GAME GAME { get; set; }
        public virtual ORDERHEADER ORDERHEADER { get; set; }
    }
}
