//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW
    {
        public int MemberId { get; set; }
        public int GameId { get; set; }
        public string ReviewText { get; set; }
        public int Rating { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual GAME GAME { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
